### ISSUE TITLE
Reminiscens redeploy checklist

### ISSUE THREAD

**Issue by cdparra** [cdparra/reminiscens#10]
- [ ] Migrate the life-api to latest play version (this might entail intensive work in adapting models of the platform) 
- [ ] Allow for lifestories to be associated to other entities like "communities" or "organizations", instead of only singe "person" 
- [ ] Deploy the server in heroku
- [ ] Package the server to be easily deployed in a server
- [ ] Make sure a web-browser version of the UI works fine and deploy it in heroku
